# Generated by Django 6.1.1 on 2026-09-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='her0_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
