# Generated by Django 6.1.1 on 2026-09-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_her0_description_about_hero_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='her0_description',
            new_name='hero_description',
        ),
    ]
