# Generated by Django 6.1.1 on 2026-09-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_her0_description_about_hero_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='intro_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
