# Generated by Django 6.1.1 on 2026-09-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_intro_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='hero_title',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='intro_title',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
