# Generated by Django 6.1.1 on 2026-09-09 11:09

import core.utils.file
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('site_slogan', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.utils.file.DynamicPath('logo'))),
                ('description', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('favicon', models.FileField(blank=True, null=True, upload_to=core.utils.file.DynamicPath('favicon'), validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'ico', 'jpe', 'jpg', 'jpeg'])])),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
