# Generated by Django 6.1.1 on 2026-09-17 11:26

import core.utils.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='about',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.AddField(
            model_name='company',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.file.DynamicPath('company/hero')),
        ),
    ]
